export const SCREENS = {
  MAIN_MENU: 'MAIN_MENU', MAP: 'MAP', BATTLE: 'BATTLE',
  BATTLE_REWARD: 'BATTLE_REWARD', SHOP: 'SHOP', REST: 'REST',
  EVENT: 'EVENT', GAME_OVER: 'GAME_OVER', VICTORY: 'VICTORY',
}

export const NODE_TYPES = {
  BATTLE: 'BATTLE', ELITE: 'ELITE', REST: 'REST', SHOP: 'SHOP',
  EVENT: 'EVENT', BOSS: 'BOSS', TREASURE: 'TREASURE',
}

export const STATUS = {
  VULNERABLE: 'VULNERABLE', WEAK: 'WEAK', FRAIL: 'FRAIL',
  STRENGTH: 'STRENGTH', DEXTERITY: 'DEXTERITY', RITUAL: 'RITUAL',
  POISON: 'POISON', ARTIFACT: 'ARTIFACT', FLEX_STRENGTH: 'FLEX_STRENGTH',
  METALLICIZE: 'METALLICIZE', FEEL_NO_PAIN: 'FEEL_NO_PAIN',
  DEMON_FORM: 'DEMON_FORM', BARRICADE: 'BARRICADE',
  DOUBLE_TAP: 'DOUBLE_TAP', AMPLIFY: 'AMPLIFY',
}

export const INTENT_TYPES = {
  ATTACK: 'ATTACK', DEFEND: 'DEFEND', BUFF: 'BUFF', DEBUFF: 'DEBUFF', SLEEP: 'SLEEP',
}
